// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bike struct {
	ID        string `json:"id"`
	OwnerName string `json:"ownerName"`
	Type      string `json:"type"`
	Make      string `json:"make"`
	Serial    string `json:"serial"`
	RenteeID  string `json:"renteeId"`
}

type Mutation struct {
}

type NewBike struct {
	OwnerName string  `json:"ownerName"`
	Type      *string `json:"type,omitempty"`
	Make      *string `json:"make,omitempty"`
	Serial    *string `json:"serial,omitempty"`
}

type NewRenteeInput struct {
	FirstName        string   `json:"firstName"`
	LastName         string   `json:"lastName"`
	NationalIDNumber string   `json:"nationalIdNumber"`
	Phone            string   `json:"phone"`
	Email            string   `json:"email"`
	HeldBikes        []string `json:"heldBikes"`
}

type Query struct {
}

type Rentee struct {
	ID               string   `json:"id"`
	FirstName        string   `json:"firstName"`
	LastName         string   `json:"lastName"`
	NationalIDNumber string   `json:"nationalIdNumber"`
	Phone            string   `json:"phone"`
	Email            string   `json:"email"`
	HeldBikes        []string `json:"heldBikes"`
}

type RenteeInput struct {
	ID               string   `json:"id"`
	FirstName        string   `json:"firstName"`
	LastName         string   `json:"lastName"`
	NationalIDNumber string   `json:"nationalIdNumber"`
	Phone            string   `json:"phone"`
	Email            string   `json:"email"`
	HeldBikes        []string `json:"heldBikes"`
}

type UpdateBikeInput struct {
	ID        string  `json:"id"`
	Type      *string `json:"type,omitempty"`
	Make      *string `json:"make,omitempty"`
	Serial    *string `json:"serial,omitempty"`
	OwnerName *string `json:"ownerName,omitempty"`
}
